service: aws-serverless

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${opt:stage, "dev"}-devicedata
    DYNAMODB_BATTERY_TABLE: ${opt:stage, "dev"}-batterydata
  iam:
    role:
        statements:
          - Effect: Allow
            Action:
              - dynamodb:*
            Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"

functions:
  deviceupload:
    handler: lib/auth.deviceupload
    environment:
      DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
      DYNAMODB_BATTERY_TABLE: ${self:provider.environment.DYNAMODB_BATTERY_TABLE}
    events:
      - http:
          path: /api/deviceupload
          method: POST
          cors: true
  getdevicestate:
    handler: lib/auth.getdevicestate
    environment:
      DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_BATTERY_TABLE}
      DYNAMODB_BATTERY_TABLE: ${self:provider.environment.DYNAMODB_BATTERY_TABLE}
    events:
      - http:
          path: /api/getdevicestate
          method: GET
          cors: true
  alldevicestate:
    handler: lib/auth.alldevicestate
    environment:
      DYNAMODB_TABLE: ${self:provider.environment.DYNAMODB_TABLE}
      DYNAMODB_BATTERY_TABLE: ${self:provider.environment.DYNAMODB_BATTERY_TABLE}
    events:
      - http:
          path: /api/alldevicestate
          method: POST
          cors: true

resources:
  Resources:
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: serial_number
            AttributeType: S
          - AttributeName: created_date
            AttributeType: S
        KeySchema:
          - AttributeName: serial_number
            KeyType: HASH
          - AttributeName: created_date
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
    BatteryDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: serial_number
            AttributeType: S
        KeySchema:
          - AttributeName: serial_number
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_BATTERY_TABLE}

plugins:
  - serverless-python-requirements
